import React from 'react'
import Head from 'next/head'

function PageHead({pageTitle, pageDescription}) {
  return (
    <Head>
      <title>{pageTitle ? pageTitle : 'Events Next App'}</title>
      <meta name="description" content={pageDescription ? pageDescription : 'Generated by create next app'} />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default PageHead