import React from 'react'
import Head from 'next/head'

const captions = {
  default: {
    title: 'Events Next App',
    descriotion: 'Generated by create next app',
  },
}

function PageHead({pageTitle, pageDescription}) {
  return (
    <Head>
      <title>{pageTitle ? pageTitle : captions.default.title}</title>
      <meta name="description" content={pageDescription ? pageDescription : captions.default.descriotion} />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default PageHead