import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
  const {events_categories} = await import('/data/data.json')

  return {
    props: {
      homeTitle: 'Home Page Title!',
      events: events_categories,
    }
  }
}

export default function Home({events, homeTitle}) {
  return (
    <>
      <Head>
        <title>Events Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={100}
            height={20}
            priority
          />
          <Link href='/'>Home</Link>
          <Link href='/events'>Events</Link>
          <Link href='/about'>About Us</Link>
        </nav>
      </header>
      <main className={styles.main}>
        <h1>{homeTitle}</h1>
        {events.map(event => (
          <Link key={event.id} href={`/events/${event.id}`} title={event.title} passHref legacyBehavior>
            <a>
              <Image src={event.image} alt={event.title} loading='lazy' width='180' height='180' />
              <h2>{event.title}</h2>
              <p>{event.description}</p>
            </a>
          </Link>
        ))}
      </main>
      <footer className={styles.footer}>
        <Image
          src="/vercel.svg"
          alt="Vercel Logo"
          className={styles.vercelLogo}
          width={100}
          height={24}
          priority
        />
        <p>
          Created 2023 @ Copyright
        </p>
      </footer>
    </>
  )
}
